global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['flask_app:4500']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']